In [21]:
import pandas as pd
import numpy as np
import seaborn as sns
from sklearn import linear_model

In [22]:
df = pd.read_csv('homeprices.csv')
df

   area  bedrooms  age   price
0  2600       3.0   20  550000
1  3000       4.0   15  565000
2  3200       NaN   18  610000
3  3600       3.0   30  595000
4  4000       5.0    8  760000
5  4100       6.0    8  810000

In [23]:
median = df['bedrooms'].median()

In [24]:
df.fillna({'bedrooms': median} , inplace=True)

In [25]:
df

   area  bedrooms  age   price
0  2600       3.0   20  550000
1  3000       4.0   15  565000
2  3200       4.0   18  610000
3  3600       3.0   30  595000
4  4000       5.0    8  760000
5  4100       6.0    8  810000

In [26]:
reg = linear_model.LinearRegression()

In [27]:
reg.fit(df[['area' , 'bedrooms' , 'age']] , df.price)
# we will predict price

LinearRegression()

In [28]:
reg.coef_

array([  112.06244194, 23388.88007794, -3231.71790863])

In [29]:
reg.intercept_

np.float64(221323.0018654043)

In [30]:
# we want 3000 sqr ft area , 3 bedrooms , 40 year old
reg.predict([[3000 , 3 ,40]])

c:\Users\SWARAJ\OneDrive\Desktop\ML\venv\Lib\site-packages\sklearn\base.py:493: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(

array([498408.25158031])

In [31]:
# price  = m1 * area + m2 * bedrooms + m3 * age + b

In [32]:
from word2number import w2n

In [33]:
import pandas as pd
new_df = pd.read_csv('hiring.csv')
new_df

  experience  test_score(out of 10)  interview_score(out of 10)  salary($)
0        NaN                    8.0                           9      50000
1        NaN                    8.0                           6      45000
2       five                    6.0                           7      60000
3        two                   10.0                          10      65000
4      seven                    9.0                           6      70000
5      three                    7.0                          10      62000
6        ten                    NaN                           7      72000
7     eleven                    7.0                           8      80000

In [34]:
new_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8 entries, 0 to 7
Data columns (total 4 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   experience                  6 non-null      object
 1   test_score(out of 10)       7 non-null      float64
 2   interview_score(out of 10)  8 non-null      int64
 3   salary($)                   8 non-null      int64
dtypes: float64(1), int64(2), object(1)
memory usage: 388.0+ bytes

In [35]:
new_df.isnull().sum()

experience                    2
test_score(out of 10)         1
interview_score(out of 10)    0
salary($)                     0
dtype: int64

In [36]:
new_df.dtypes

experience                     object
test_score(out of 10)         float64
interview_score(out of 10)      int64
salary($)                       int64
dtype: object

In [37]:
new_df['experience'] = new_df['experience'].fillna('zero')

In [38]:
new_df

  experience  test_score(out of 10)  interview_score(out of 10)  salary($)
0       zero                    8.0                           9      50000
1       zero                    8.0                           6      45000
2       five                    6.0                           7      60000
3        two                   10.0                          10      65000
4      seven                    9.0                           6      70000
5      three                    7.0                          10      62000
6        ten                    NaN                           7      72000
7     eleven                    7.0                           8      80000

In [39]:
new_df['test_score(out of 10)'].fillna(new_df['test_score(out of 10)'].mean() , inplace=True)

C:\Users\SWARAJ\AppData\Local\Temp\ipykernel_24848\2547830648.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  new_df['test_score(out of 10)'].fillna(new_df['test_score(out of 10)'].mean() , inplace=True)

In [40]:

new_df

  experience  test_score(out of 10)  interview_score(out of 10)  salary($)
0       zero               8.000000                           9      50000
1       zero               8.000000                           6      45000
2       five               6.000000                           7      60000
3        two              10.000000                          10      65000
4      seven               9.000000                           6      70000
5      three               7.000000                          10      62000
6        ten               7.857143                           7      72000
7     eleven               7.000000                           8      80000

In [41]:
from word2number import w2n
new_df['experience_words'] = new_df['experience'].apply(w2n.word_to_num)

In [42]:
new_df

,experience,test_score(out of 10),interview_score(out of 10),salary($),experience_words
0,zero,8.000000,9,50000,0
1,zero,8.000000,6,45000,0
2,five,6.000000,7,60000,5
3,two,10.000000,10,65000,2
4,seven,9.000000,6,70000,7
5,three,7.000000,10,62000,3
6,ten,7.857143,7,72000,10
7,eleven,7.000000,8,80000,11

In [43]:
new_df.drop(columns=['experience'] ,axis=1)

,test_score(out of 10),interview_score(out of 10),salary($),experience_words
0,8.000000,9,50000,0
1,8.000000,6,45000,0
2,6.000000,7,60000,5
3,10.000000,10,65000,2
4,9.000000,6,70000,7
5,7.000000,10,62000,3
6,7.857143,7,72000,10
7,7.000000,8,80000,11

In [44]:
from sklearn import linear_model
model = linear_model.LinearRegression()

In [45]:
model.fit(new_df[['experience_words' , 'test_score(out of 10)',	'interview_score(out of 10)']] , new_df['salary($)'])

LinearRegression()

In [47]:
model.predict([[2,9,6]])

c:\Users\SWARAJ\OneDrive\Desktop\ML\venv\Lib\site-packages\sklearn\base.py:493: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(

array([53290.89255945])