In [1]:
import pandas as pd
import numpy as np

In [2]:
dict1 = {
    "name" : ['swaraj' , 'yuvraj' , 'shweta' , 'vinod' , 'shravani'],
    "marks":[23,2,4,6,765],
    "city" : ['mumbai' , 'delhi' , 'guwahati' , 'kerala' , 'kedarnath'],
}

In [3]:
df = pd.DataFrame(dict1)

In [4]:
df

       name  marks       city
0    swaraj     23     mumbai
1    yuvraj      2      delhi
2    shweta      4   guwahati
3     vinod      6     kerala
4  shravani    765  kedarnath

In [5]:
df.to_csv('demo.csv' , index =False)

In [6]:
df.head(2)

     name  marks    city
0  swaraj     23  mumbai
1  yuvraj      2   delhi

**shows first 2 rows

In [7]:
df.tail(3)

       name  marks       city
2    shweta      4   guwahati
3     vinod      6     kerala
4  shravani    765  kedarnath

**shows last 3 rows

In [8]:
df.describe()

            marks
count    5.000000
mean   160.000000
std    338.308291
min      2.000000
25%      4.000000
50%      6.000000
75%     23.000000
max    765.000000

**will give the description of numerical columns

In [9]:
swaraj = pd.read_csv('demo.csv')

In [10]:
swaraj

       name  marks       city
0    swaraj     23     mumbai
1    yuvraj      2      delhi
2    shweta      4   guwahati
3     vinod      6     kerala
4  shravani    765  kedarnath

In [11]:
swaraj['name']

0      swaraj
1      yuvraj
2      shweta
3       vinod
4    shravani
Name: name, dtype: object

In [12]:
swaraj['name'][0]

'swaraj'

In [13]:
swaraj['name'][0] = 'swaraaaajjjjjj'

C:\Users\SWARAJ\AppData\Local\Temp\ipykernel_3048\3936413159.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  swaraj['name'][0] = 'swaraaaajjjjjj'

In [14]:
swaraj.to_csv('demo.csv')

In [15]:
swaraj.index = ['first' , 'second' , 'third' , 'fourth', 'fifth']

In [16]:
swaraj

                  name  marks       city
first   swaraaaajjjjjj     23     mumbai
second          yuvraj      2      delhi
third           shweta      4   guwahati
fourth           vinod      6     kerala
fifth         shravani    765  kedarnath

In [17]:
ser = pd.Series(np.random.rand(34))

In [18]:
ser

0     0.038695
1     0.040764
2     0.300571
3     0.765781
4     0.586743
5     0.335673
6     0.540867
7     0.667854
8     0.740821
9     0.663649
10    0.939309
11    0.828477
12    0.269193
13    0.449341
14    0.149916
15    0.297806
16    0.009160
17    0.754814
18    0.765586
19    0.922553
20    0.086371
21    0.621891
22    0.713473
23    0.169808
24    0.180527
25    0.647612
26    0.499870
27    0.458754
28    0.336989
29    0.755645
30    0.566523
31    0.044710
32    0.332693
33    0.553508
dtype: float64

In [19]:
newdf = pd.DataFrame(np.random.rand(30 ,5) , index = np.arange(30))

In [20]:
newdf

           0         1         2         3         4
0   0.046576  0.735467  0.795357  0.215610  0.439311
1   0.974708  0.977364  0.047705  0.881846  0.593464
2   0.729369  0.938428  0.750857  0.206948  0.903578
3   0.559799  0.291343  0.210588  0.130580  0.408843
4   0.417399  0.163797  0.949930  0.106922  0.787961
5   0.382054  0.581325  0.319447  0.198870  0.836659
6   0.815086  0.569530  0.670247  0.476553  0.026439
7   0.637491  0.563575  0.525609  0.822204  0.660467
8   0.179158  0.250103  0.877241  0.812549  0.150857
9   0.993249  0.257883  0.615360  0.895088  0.790843
10  0.138236  0.531602  0.356417  0.668148  0.559726
11  0.524640  0.629824  0.242595  0.400929  0.702015
12  0.684755  0.334938  0.313693  0.930175  0.585499
13  0.266588  0.474940  0.266275  0.441674  0.395713
14  0.455457  0.637871  0.368211  0.122079  0.126587
15  0.858224  0.936869  0.482133  0.081293  0.392729
16  0.062572  0.599580  0.480885  0.174895  0.563188
17  0.774109  0.018156  0.123902  0.070437  0.928040
18  0.363421  0.191635  0.586196  0.366963  0.752340
19  0.485237  0.185309  0.030708  0.351871  0.967544
20  0.977664  0.998294  0.614662  0.500555  0.285836
21  0.819907  0.187399  0.644267  0.660974  0.531760
22  0.213325  0.025167  0.755809  0.727461  0.256234
23  0.099218  0.341354  0.857135  0.148885  0.998354
24  0.479205  0.046781  0.589983  0.661204  0.082925
25  0.788304  0.880605  0.069389  0.675728  0.844861
26  0.948223  0.194041  0.468253  0.976434  0.604738
27  0.125640  0.606567  0.152246  0.721828  0.090892
28  0.339934  0.198164  0.076613  0.794165  0.241896
29  0.165941  0.224751  0.582694  0.767736  0.745386

In [21]:
newdf.to_numpy()

array([[0.04657637, 0.735467  , 0.79535682, 0.21561   , 0.43931145],
       [0.97470797, 0.97736373, 0.04770473, 0.88184588, 0.59346377],
       [0.72936886, 0.93842785, 0.75085666, 0.20694822, 0.90357817],
       [0.55979859, 0.29134264, 0.2105879 , 0.13057961, 0.40884331],
       [0.41739934, 0.16379728, 0.94993041, 0.10692219, 0.78796073],
       [0.38205433, 0.58132479, 0.31944666, 0.19886955, 0.83665857],
       [0.81508554, 0.56952972, 0.67024681, 0.47655323, 0.02643904],
       [0.63749093, 0.56357499, 0.52560916, 0.82220419, 0.66046667],
       [0.17915767, 0.2501025 , 0.87724052, 0.81254929, 0.15085659],
       [0.99324883, 0.25788327, 0.61536   , 0.89508769, 0.79084269],
       [0.13823556, 0.53160168, 0.35641711, 0.6681484 , 0.55972566],
       [0.52464024, 0.62982394, 0.24259475, 0.40092945, 0.70201502],
       [0.68475518, 0.33493803, 0.31369339, 0.93017533, 0.58549918],
       [0.2665883 , 0.47494036, 0.26627467, 0.44167445, 0.39571286],
       [0.45545665, 0.63787089, 0.3682111 , 0.12207946, 0.12658663],
       [0.85822446, 0.93686916, 0.48213334, 0.08129315, 0.39272911],
       [0.06257173, 0.59957952, 0.48088475, 0.17489496, 0.56318807],
       [0.77410941, 0.018156  , 0.12390154, 0.07043683, 0.92804034],
       [0.36342069, 0.19163452, 0.58619599, 0.36696259, 0.7523397 ],
       [0.48523743, 0.18530946, 0.03070771, 0.35187099, 0.96754362],
       [0.97766392, 0.99829398, 0.61466224, 0.50055489, 0.28583579],
       [0.81990741, 0.1873992 , 0.64426701, 0.66097371, 0.53176045],
       [0.21332481, 0.02516696, 0.75580949, 0.72746095, 0.25623398],
       [0.09921825, 0.34135438, 0.8571346 , 0.14888469, 0.99835386],
       [0.4792051 , 0.04678061, 0.58998289, 0.66120414, 0.08292515],
       [0.78830408, 0.880605  , 0.06938898, 0.67572754, 0.84486094],
       [0.94822255, 0.19404148, 0.46825273, 0.97643444, 0.60473782],
       [0.12563953, 0.60656739, 0.1522455 , 0.72182794, 0.09089197],
       [0.33993366, 0.19816412, 0.07661268, 0.79416542, 0.24189626],
       [0.16594145, 0.22475129, 0.58269444, 0.76773643, 0.74538571]])

In [22]:
newdf.sort_index(axis = 0 ,ascending = False)

           0         1         2         3         4
29  0.165941  0.224751  0.582694  0.767736  0.745386
28  0.339934  0.198164  0.076613  0.794165  0.241896
27  0.125640  0.606567  0.152246  0.721828  0.090892
26  0.948223  0.194041  0.468253  0.976434  0.604738
25  0.788304  0.880605  0.069389  0.675728  0.844861
24  0.479205  0.046781  0.589983  0.661204  0.082925
23  0.099218  0.341354  0.857135  0.148885  0.998354
22  0.213325  0.025167  0.755809  0.727461  0.256234
21  0.819907  0.187399  0.644267  0.660974  0.531760
20  0.977664  0.998294  0.614662  0.500555  0.285836
19  0.485237  0.185309  0.030708  0.351871  0.967544
18  0.363421  0.191635  0.586196  0.366963  0.752340
17  0.774109  0.018156  0.123902  0.070437  0.928040
16  0.062572  0.599580  0.480885  0.174895  0.563188
15  0.858224  0.936869  0.482133  0.081293  0.392729
14  0.455457  0.637871  0.368211  0.122079  0.126587
13  0.266588  0.474940  0.266275  0.441674  0.395713
12  0.684755  0.334938  0.313693  0.930175  0.585499
11  0.524640  0.629824  0.242595  0.400929  0.702015
10  0.138236  0.531602  0.356417  0.668148  0.559726
9   0.993249  0.257883  0.615360  0.895088  0.790843
8   0.179158  0.250103  0.877241  0.812549  0.150857
7   0.637491  0.563575  0.525609  0.822204  0.660467
6   0.815086  0.569530  0.670247  0.476553  0.026439
5   0.382054  0.581325  0.319447  0.198870  0.836659
4   0.417399  0.163797  0.949930  0.106922  0.787961
3   0.559799  0.291343  0.210588  0.130580  0.408843
2   0.729369  0.938428  0.750857  0.206948  0.903578
1   0.974708  0.977364  0.047705  0.881846  0.593464
0   0.046576  0.735467  0.795357  0.215610  0.439311

In [23]:
newdf.sort_index(axis = 1,ascending = False)

           4         3         2         1         0
0   0.439311  0.215610  0.795357  0.735467  0.046576
1   0.593464  0.881846  0.047705  0.977364  0.974708
2   0.903578  0.206948  0.750857  0.938428  0.729369
3   0.408843  0.130580  0.210588  0.291343  0.559799
4   0.787961  0.106922  0.949930  0.163797  0.417399
5   0.836659  0.198870  0.319447  0.581325  0.382054
6   0.026439  0.476553  0.670247  0.569530  0.815086
7   0.660467  0.822204  0.525609  0.563575  0.637491
8   0.150857  0.812549  0.877241  0.250103  0.179158
9   0.790843  0.895088  0.615360  0.257883  0.993249
10  0.559726  0.668148  0.356417  0.531602  0.138236
11  0.702015  0.400929  0.242595  0.629824  0.524640
12  0.585499  0.930175  0.313693  0.334938  0.684755
13  0.395713  0.441674  0.266275  0.474940  0.266588
14  0.126587  0.122079  0.368211  0.637871  0.455457
15  0.392729  0.081293  0.482133  0.936869  0.858224
16  0.563188  0.174895  0.480885  0.599580  0.062572
17  0.928040  0.070437  0.123902  0.018156  0.774109
18  0.752340  0.366963  0.586196  0.191635  0.363421
19  0.967544  0.351871  0.030708  0.185309  0.485237
20  0.285836  0.500555  0.614662  0.998294  0.977664
21  0.531760  0.660974  0.644267  0.187399  0.819907
22  0.256234  0.727461  0.755809  0.025167  0.213325
23  0.998354  0.148885  0.857135  0.341354  0.099218
24  0.082925  0.661204  0.589983  0.046781  0.479205
25  0.844861  0.675728  0.069389  0.880605  0.788304
26  0.604738  0.976434  0.468253  0.194041  0.948223
27  0.090892  0.721828  0.152246  0.606567  0.125640
28  0.241896  0.794165  0.076613  0.198164  0.339934
29  0.745386  0.767736  0.582694  0.224751  0.165941

In [24]:
newdf2 = newdf

**newdf2 and newdf both point to the same DataFrame , any changes made in newdf2 will be reflected in newdf

In [25]:
newdf2 = newdf.copy()

** now both points to its own dataframe

 **everytime u want to set a value in a dataframe use the loc function

In [26]:
newdf.loc[0,0]=212

In [27]:
newdf

             0         1         2         3         4
0   212.000000  0.735467  0.795357  0.215610  0.439311
1     0.974708  0.977364  0.047705  0.881846  0.593464
2     0.729369  0.938428  0.750857  0.206948  0.903578
3     0.559799  0.291343  0.210588  0.130580  0.408843
4     0.417399  0.163797  0.949930  0.106922  0.787961
5     0.382054  0.581325  0.319447  0.198870  0.836659
6     0.815086  0.569530  0.670247  0.476553  0.026439
7     0.637491  0.563575  0.525609  0.822204  0.660467
8     0.179158  0.250103  0.877241  0.812549  0.150857
9     0.993249  0.257883  0.615360  0.895088  0.790843
10    0.138236  0.531602  0.356417  0.668148  0.559726
11    0.524640  0.629824  0.242595  0.400929  0.702015
12    0.684755  0.334938  0.313693  0.930175  0.585499
13    0.266588  0.474940  0.266275  0.441674  0.395713
14    0.455457  0.637871  0.368211  0.122079  0.126587
15    0.858224  0.936869  0.482133  0.081293  0.392729
16    0.062572  0.599580  0.480885  0.174895  0.563188
17    0.774109  0.018156  0.123902  0.070437  0.928040
18    0.363421  0.191635  0.586196  0.366963  0.752340
19    0.485237  0.185309  0.030708  0.351871  0.967544
20    0.977664  0.998294  0.614662  0.500555  0.285836
21    0.819907  0.187399  0.644267  0.660974  0.531760
22    0.213325  0.025167  0.755809  0.727461  0.256234
23    0.099218  0.341354  0.857135  0.148885  0.998354
24    0.479205  0.046781  0.589983  0.661204  0.082925
25    0.788304  0.880605  0.069389  0.675728  0.844861
26    0.948223  0.194041  0.468253  0.976434  0.604738
27    0.125640  0.606567  0.152246  0.721828  0.090892
28    0.339934  0.198164  0.076613  0.794165  0.241896
29    0.165941  0.224751  0.582694  0.767736  0.745386

In [28]:
newdf.columns

RangeIndex(start=0, stop=5, step=1)

In [29]:
newdf.columns = list("ABCDE")

In [30]:
newdf

             A         B         C         D         E
0   212.000000  0.735467  0.795357  0.215610  0.439311
1     0.974708  0.977364  0.047705  0.881846  0.593464
2     0.729369  0.938428  0.750857  0.206948  0.903578
3     0.559799  0.291343  0.210588  0.130580  0.408843
4     0.417399  0.163797  0.949930  0.106922  0.787961
5     0.382054  0.581325  0.319447  0.198870  0.836659
6     0.815086  0.569530  0.670247  0.476553  0.026439
7     0.637491  0.563575  0.525609  0.822204  0.660467
8     0.179158  0.250103  0.877241  0.812549  0.150857
9     0.993249  0.257883  0.615360  0.895088  0.790843
10    0.138236  0.531602  0.356417  0.668148  0.559726
11    0.524640  0.629824  0.242595  0.400929  0.702015
12    0.684755  0.334938  0.313693  0.930175  0.585499
13    0.266588  0.474940  0.266275  0.441674  0.395713
14    0.455457  0.637871  0.368211  0.122079  0.126587
15    0.858224  0.936869  0.482133  0.081293  0.392729
16    0.062572  0.599580  0.480885  0.174895  0.563188
17    0.774109  0.018156  0.123902  0.070437  0.928040
18    0.363421  0.191635  0.586196  0.366963  0.752340
19    0.485237  0.185309  0.030708  0.351871  0.967544
20    0.977664  0.998294  0.614662  0.500555  0.285836
21    0.819907  0.187399  0.644267  0.660974  0.531760
22    0.213325  0.025167  0.755809  0.727461  0.256234
23    0.099218  0.341354  0.857135  0.148885  0.998354
24    0.479205  0.046781  0.589983  0.661204  0.082925
25    0.788304  0.880605  0.069389  0.675728  0.844861
26    0.948223  0.194041  0.468253  0.976434  0.604738
27    0.125640  0.606567  0.152246  0.721828  0.090892
28    0.339934  0.198164  0.076613  0.794165  0.241896
29    0.165941  0.224751  0.582694  0.767736  0.745386

In [31]:
newdf.columns = [1,2,3,4,5]

In [32]:
newdf

             1         2         3         4         5
0   212.000000  0.735467  0.795357  0.215610  0.439311
1     0.974708  0.977364  0.047705  0.881846  0.593464
2     0.729369  0.938428  0.750857  0.206948  0.903578
3     0.559799  0.291343  0.210588  0.130580  0.408843
4     0.417399  0.163797  0.949930  0.106922  0.787961
5     0.382054  0.581325  0.319447  0.198870  0.836659
6     0.815086  0.569530  0.670247  0.476553  0.026439
7     0.637491  0.563575  0.525609  0.822204  0.660467
8     0.179158  0.250103  0.877241  0.812549  0.150857
9     0.993249  0.257883  0.615360  0.895088  0.790843
10    0.138236  0.531602  0.356417  0.668148  0.559726
11    0.524640  0.629824  0.242595  0.400929  0.702015
12    0.684755  0.334938  0.313693  0.930175  0.585499
13    0.266588  0.474940  0.266275  0.441674  0.395713
14    0.455457  0.637871  0.368211  0.122079  0.126587
15    0.858224  0.936869  0.482133  0.081293  0.392729
16    0.062572  0.599580  0.480885  0.174895  0.563188
17    0.774109  0.018156  0.123902  0.070437  0.928040
18    0.363421  0.191635  0.586196  0.366963  0.752340
19    0.485237  0.185309  0.030708  0.351871  0.967544
20    0.977664  0.998294  0.614662  0.500555  0.285836
21    0.819907  0.187399  0.644267  0.660974  0.531760
22    0.213325  0.025167  0.755809  0.727461  0.256234
23    0.099218  0.341354  0.857135  0.148885  0.998354
24    0.479205  0.046781  0.589983  0.661204  0.082925
25    0.788304  0.880605  0.069389  0.675728  0.844861
26    0.948223  0.194041  0.468253  0.976434  0.604738
27    0.125640  0.606567  0.152246  0.721828  0.090892
28    0.339934  0.198164  0.076613  0.794165  0.241896
29    0.165941  0.224751  0.582694  0.767736  0.745386

In [33]:
newdf.drop(5 , axis = 1)

             1         2         3         4
0   212.000000  0.735467  0.795357  0.215610
1     0.974708  0.977364  0.047705  0.881846
2     0.729369  0.938428  0.750857  0.206948
3     0.559799  0.291343  0.210588  0.130580
4     0.417399  0.163797  0.949930  0.106922
5     0.382054  0.581325  0.319447  0.198870
6     0.815086  0.569530  0.670247  0.476553
7     0.637491  0.563575  0.525609  0.822204
8     0.179158  0.250103  0.877241  0.812549
9     0.993249  0.257883  0.615360  0.895088
10    0.138236  0.531602  0.356417  0.668148
11    0.524640  0.629824  0.242595  0.400929
12    0.684755  0.334938  0.313693  0.930175
13    0.266588  0.474940  0.266275  0.441674
14    0.455457  0.637871  0.368211  0.122079
15    0.858224  0.936869  0.482133  0.081293
16    0.062572  0.599580  0.480885  0.174895
17    0.774109  0.018156  0.123902  0.070437
18    0.363421  0.191635  0.586196  0.366963
19    0.485237  0.185309  0.030708  0.351871
20    0.977664  0.998294  0.614662  0.500555
21    0.819907  0.187399  0.644267  0.660974
22    0.213325  0.025167  0.755809  0.727461
23    0.099218  0.341354  0.857135  0.148885
24    0.479205  0.046781  0.589983  0.661204
25    0.788304  0.880605  0.069389  0.675728
26    0.948223  0.194041  0.468253  0.976434
27    0.125640  0.606567  0.152246  0.721828
28    0.339934  0.198164  0.076613  0.794165
29    0.165941  0.224751  0.582694  0.767736

In [34]:
newdf.loc[0,'A'] = 11111

In [35]:
newdf

             1         2         3         4         5        A
0   212.000000  0.735467  0.795357  0.215610  0.439311  11111.0
1     0.974708  0.977364  0.047705  0.881846  0.593464      NaN
2     0.729369  0.938428  0.750857  0.206948  0.903578      NaN
3     0.559799  0.291343  0.210588  0.130580  0.408843      NaN
4     0.417399  0.163797  0.949930  0.106922  0.787961      NaN
5     0.382054  0.581325  0.319447  0.198870  0.836659      NaN
6     0.815086  0.569530  0.670247  0.476553  0.026439      NaN
7     0.637491  0.563575  0.525609  0.822204  0.660467      NaN
8     0.179158  0.250103  0.877241  0.812549  0.150857      NaN
9     0.993249  0.257883  0.615360  0.895088  0.790843      NaN
10    0.138236  0.531602  0.356417  0.668148  0.559726      NaN
11    0.524640  0.629824  0.242595  0.400929  0.702015      NaN
12    0.684755  0.334938  0.313693  0.930175  0.585499      NaN
13    0.266588  0.474940  0.266275  0.441674  0.395713      NaN
14    0.455457  0.637871  0.368211  0.122079  0.126587      NaN
15    0.858224  0.936869  0.482133  0.081293  0.392729      NaN
16    0.062572  0.599580  0.480885  0.174895  0.563188      NaN
17    0.774109  0.018156  0.123902  0.070437  0.928040      NaN
18    0.363421  0.191635  0.586196  0.366963  0.752340      NaN
19    0.485237  0.185309  0.030708  0.351871  0.967544      NaN
20    0.977664  0.998294  0.614662  0.500555  0.285836      NaN
21    0.819907  0.187399  0.644267  0.660974  0.531760      NaN
22    0.213325  0.025167  0.755809  0.727461  0.256234      NaN
23    0.099218  0.341354  0.857135  0.148885  0.998354      NaN
24    0.479205  0.046781  0.589983  0.661204  0.082925      NaN
25    0.788304  0.880605  0.069389  0.675728  0.844861      NaN
26    0.948223  0.194041  0.468253  0.976434  0.604738      NaN
27    0.125640  0.606567  0.152246  0.721828  0.090892      NaN
28    0.339934  0.198164  0.076613  0.794165  0.241896      NaN
29    0.165941  0.224751  0.582694  0.767736  0.745386      NaN

In [36]:
newdf.drop("A" ,axis =1)

             1         2         3         4         5
0   212.000000  0.735467  0.795357  0.215610  0.439311
1     0.974708  0.977364  0.047705  0.881846  0.593464
2     0.729369  0.938428  0.750857  0.206948  0.903578
3     0.559799  0.291343  0.210588  0.130580  0.408843
4     0.417399  0.163797  0.949930  0.106922  0.787961
5     0.382054  0.581325  0.319447  0.198870  0.836659
6     0.815086  0.569530  0.670247  0.476553  0.026439
7     0.637491  0.563575  0.525609  0.822204  0.660467
8     0.179158  0.250103  0.877241  0.812549  0.150857
9     0.993249  0.257883  0.615360  0.895088  0.790843
10    0.138236  0.531602  0.356417  0.668148  0.559726
11    0.524640  0.629824  0.242595  0.400929  0.702015
12    0.684755  0.334938  0.313693  0.930175  0.585499
13    0.266588  0.474940  0.266275  0.441674  0.395713
14    0.455457  0.637871  0.368211  0.122079  0.126587
15    0.858224  0.936869  0.482133  0.081293  0.392729
16    0.062572  0.599580  0.480885  0.174895  0.563188
17    0.774109  0.018156  0.123902  0.070437  0.928040
18    0.363421  0.191635  0.586196  0.366963  0.752340
19    0.485237  0.185309  0.030708  0.351871  0.967544
20    0.977664  0.998294  0.614662  0.500555  0.285836
21    0.819907  0.187399  0.644267  0.660974  0.531760
22    0.213325  0.025167  0.755809  0.727461  0.256234
23    0.099218  0.341354  0.857135  0.148885  0.998354
24    0.479205  0.046781  0.589983  0.661204  0.082925
25    0.788304  0.880605  0.069389  0.675728  0.844861
26    0.948223  0.194041  0.468253  0.976434  0.604738
27    0.125640  0.606567  0.152246  0.721828  0.090892
28    0.339934  0.198164  0.076613  0.794165  0.241896
29    0.165941  0.224751  0.582694  0.767736  0.745386

In [37]:
newdf.loc[[1,2] , [1 , 5]]

          1         5
1  0.974708  0.593464
2  0.729369  0.903578

In [38]:
newdf.loc[[1,2] , :]

          1         2         3         4         5   A
1  0.974708  0.977364  0.047705  0.881846  0.593464 NaN
2  0.729369  0.938428  0.750857  0.206948  0.903578 NaN

In [39]:
newdf

             1         2         3         4         5        A
0   212.000000  0.735467  0.795357  0.215610  0.439311  11111.0
1     0.974708  0.977364  0.047705  0.881846  0.593464      NaN
2     0.729369  0.938428  0.750857  0.206948  0.903578      NaN
3     0.559799  0.291343  0.210588  0.130580  0.408843      NaN
4     0.417399  0.163797  0.949930  0.106922  0.787961      NaN
5     0.382054  0.581325  0.319447  0.198870  0.836659      NaN
6     0.815086  0.569530  0.670247  0.476553  0.026439      NaN
7     0.637491  0.563575  0.525609  0.822204  0.660467      NaN
8     0.179158  0.250103  0.877241  0.812549  0.150857      NaN
9     0.993249  0.257883  0.615360  0.895088  0.790843      NaN
10    0.138236  0.531602  0.356417  0.668148  0.559726      NaN
11    0.524640  0.629824  0.242595  0.400929  0.702015      NaN
12    0.684755  0.334938  0.313693  0.930175  0.585499      NaN
13    0.266588  0.474940  0.266275  0.441674  0.395713      NaN
14    0.455457  0.637871  0.368211  0.122079  0.126587      NaN
15    0.858224  0.936869  0.482133  0.081293  0.392729      NaN
16    0.062572  0.599580  0.480885  0.174895  0.563188      NaN
17    0.774109  0.018156  0.123902  0.070437  0.928040      NaN
18    0.363421  0.191635  0.586196  0.366963  0.752340      NaN
19    0.485237  0.185309  0.030708  0.351871  0.967544      NaN
20    0.977664  0.998294  0.614662  0.500555  0.285836      NaN
21    0.819907  0.187399  0.644267  0.660974  0.531760      NaN
22    0.213325  0.025167  0.755809  0.727461  0.256234      NaN
23    0.099218  0.341354  0.857135  0.148885  0.998354      NaN
24    0.479205  0.046781  0.589983  0.661204  0.082925      NaN
25    0.788304  0.880605  0.069389  0.675728  0.844861      NaN
26    0.948223  0.194041  0.468253  0.976434  0.604738      NaN
27    0.125640  0.606567  0.152246  0.721828  0.090892      NaN
28    0.339934  0.198164  0.076613  0.794165  0.241896      NaN
29    0.165941  0.224751  0.582694  0.767736  0.745386      NaN

In [40]:
newdf = newdf.drop("A" , axis =1)

In [41]:
newdf

             1         2         3         4         5
0   212.000000  0.735467  0.795357  0.215610  0.439311
1     0.974708  0.977364  0.047705  0.881846  0.593464
2     0.729369  0.938428  0.750857  0.206948  0.903578
3     0.559799  0.291343  0.210588  0.130580  0.408843
4     0.417399  0.163797  0.949930  0.106922  0.787961
5     0.382054  0.581325  0.319447  0.198870  0.836659
6     0.815086  0.569530  0.670247  0.476553  0.026439
7     0.637491  0.563575  0.525609  0.822204  0.660467
8     0.179158  0.250103  0.877241  0.812549  0.150857
9     0.993249  0.257883  0.615360  0.895088  0.790843
10    0.138236  0.531602  0.356417  0.668148  0.559726
11    0.524640  0.629824  0.242595  0.400929  0.702015
12    0.684755  0.334938  0.313693  0.930175  0.585499
13    0.266588  0.474940  0.266275  0.441674  0.395713
14    0.455457  0.637871  0.368211  0.122079  0.126587
15    0.858224  0.936869  0.482133  0.081293  0.392729
16    0.062572  0.599580  0.480885  0.174895  0.563188
17    0.774109  0.018156  0.123902  0.070437  0.928040
18    0.363421  0.191635  0.586196  0.366963  0.752340
19    0.485237  0.185309  0.030708  0.351871  0.967544
20    0.977664  0.998294  0.614662  0.500555  0.285836
21    0.819907  0.187399  0.644267  0.660974  0.531760
22    0.213325  0.025167  0.755809  0.727461  0.256234
23    0.099218  0.341354  0.857135  0.148885  0.998354
24    0.479205  0.046781  0.589983  0.661204  0.082925
25    0.788304  0.880605  0.069389  0.675728  0.844861
26    0.948223  0.194041  0.468253  0.976434  0.604738
27    0.125640  0.606567  0.152246  0.721828  0.090892
28    0.339934  0.198164  0.076613  0.794165  0.241896
29    0.165941  0.224751  0.582694  0.767736  0.745386

In [42]:
newdf.drop([0])

           1         2         3         4         5
1   0.974708  0.977364  0.047705  0.881846  0.593464
2   0.729369  0.938428  0.750857  0.206948  0.903578
3   0.559799  0.291343  0.210588  0.130580  0.408843
4   0.417399  0.163797  0.949930  0.106922  0.787961
5   0.382054  0.581325  0.319447  0.198870  0.836659
6   0.815086  0.569530  0.670247  0.476553  0.026439
7   0.637491  0.563575  0.525609  0.822204  0.660467
8   0.179158  0.250103  0.877241  0.812549  0.150857
9   0.993249  0.257883  0.615360  0.895088  0.790843
10  0.138236  0.531602  0.356417  0.668148  0.559726
11  0.524640  0.629824  0.242595  0.400929  0.702015
12  0.684755  0.334938  0.313693  0.930175  0.585499
13  0.266588  0.474940  0.266275  0.441674  0.395713
14  0.455457  0.637871  0.368211  0.122079  0.126587
15  0.858224  0.936869  0.482133  0.081293  0.392729
16  0.062572  0.599580  0.480885  0.174895  0.563188
17  0.774109  0.018156  0.123902  0.070437  0.928040
18  0.363421  0.191635  0.586196  0.366963  0.752340
19  0.485237  0.185309  0.030708  0.351871  0.967544
20  0.977664  0.998294  0.614662  0.500555  0.285836
21  0.819907  0.187399  0.644267  0.660974  0.531760
22  0.213325  0.025167  0.755809  0.727461  0.256234
23  0.099218  0.341354  0.857135  0.148885  0.998354
24  0.479205  0.046781  0.589983  0.661204  0.082925
25  0.788304  0.880605  0.069389  0.675728  0.844861
26  0.948223  0.194041  0.468253  0.976434  0.604738
27  0.125640  0.606567  0.152246  0.721828  0.090892
28  0.339934  0.198164  0.076613  0.794165  0.241896
29  0.165941  0.224751  0.582694  0.767736  0.745386

**inPlace = True makes changes in the original newdf , if we do newdf.drop() , original df is still the same just a query is 
being run on the df , but if we use inPlace  = True , the query makes changes on the original df

In [43]:
newdf.reset_index()

    index           1         2         3         4         5
0       0  212.000000  0.735467  0.795357  0.215610  0.439311
1       1    0.974708  0.977364  0.047705  0.881846  0.593464
2       2    0.729369  0.938428  0.750857  0.206948  0.903578
3       3    0.559799  0.291343  0.210588  0.130580  0.408843
4       4    0.417399  0.163797  0.949930  0.106922  0.787961
5       5    0.382054  0.581325  0.319447  0.198870  0.836659
6       6    0.815086  0.569530  0.670247  0.476553  0.026439
7       7    0.637491  0.563575  0.525609  0.822204  0.660467
8       8    0.179158  0.250103  0.877241  0.812549  0.150857
9       9    0.993249  0.257883  0.615360  0.895088  0.790843
10     10    0.138236  0.531602  0.356417  0.668148  0.559726
11     11    0.524640  0.629824  0.242595  0.400929  0.702015
12     12    0.684755  0.334938  0.313693  0.930175  0.585499
13     13    0.266588  0.474940  0.266275  0.441674  0.395713
14     14    0.455457  0.637871  0.368211  0.122079  0.126587
15     15    0.858224  0.936869  0.482133  0.081293  0.392729
16     16    0.062572  0.599580  0.480885  0.174895  0.563188
17     17    0.774109  0.018156  0.123902  0.070437  0.928040
18     18    0.363421  0.191635  0.586196  0.366963  0.752340
19     19    0.485237  0.185309  0.030708  0.351871  0.967544
20     20    0.977664  0.998294  0.614662  0.500555  0.285836
21     21    0.819907  0.187399  0.644267  0.660974  0.531760
22     22    0.213325  0.025167  0.755809  0.727461  0.256234
23     23    0.099218  0.341354  0.857135  0.148885  0.998354
24     24    0.479205  0.046781  0.589983  0.661204  0.082925
25     25    0.788304  0.880605  0.069389  0.675728  0.844861
26     26    0.948223  0.194041  0.468253  0.976434  0.604738
27     27    0.125640  0.606567  0.152246  0.721828  0.090892
28     28    0.339934  0.198164  0.076613  0.794165  0.241896
29     29    0.165941  0.224751  0.582694  0.767736  0.745386

In [44]:
newdf.reset_index(drop = True)

             1         2         3         4         5
0   212.000000  0.735467  0.795357  0.215610  0.439311
1     0.974708  0.977364  0.047705  0.881846  0.593464
2     0.729369  0.938428  0.750857  0.206948  0.903578
3     0.559799  0.291343  0.210588  0.130580  0.408843
4     0.417399  0.163797  0.949930  0.106922  0.787961
5     0.382054  0.581325  0.319447  0.198870  0.836659
6     0.815086  0.569530  0.670247  0.476553  0.026439
7     0.637491  0.563575  0.525609  0.822204  0.660467
8     0.179158  0.250103  0.877241  0.812549  0.150857
9     0.993249  0.257883  0.615360  0.895088  0.790843
10    0.138236  0.531602  0.356417  0.668148  0.559726
11    0.524640  0.629824  0.242595  0.400929  0.702015
12    0.684755  0.334938  0.313693  0.930175  0.585499
13    0.266588  0.474940  0.266275  0.441674  0.395713
14    0.455457  0.637871  0.368211  0.122079  0.126587
15    0.858224  0.936869  0.482133  0.081293  0.392729
16    0.062572  0.599580  0.480885  0.174895  0.563188
17    0.774109  0.018156  0.123902  0.070437  0.928040
18    0.363421  0.191635  0.586196  0.366963  0.752340
19    0.485237  0.185309  0.030708  0.351871  0.967544
20    0.977664  0.998294  0.614662  0.500555  0.285836
21    0.819907  0.187399  0.644267  0.660974  0.531760
22    0.213325  0.025167  0.755809  0.727461  0.256234
23    0.099218  0.341354  0.857135  0.148885  0.998354
24    0.479205  0.046781  0.589983  0.661204  0.082925
25    0.788304  0.880605  0.069389  0.675728  0.844861
26    0.948223  0.194041  0.468253  0.976434  0.604738
27    0.125640  0.606567  0.152246  0.721828  0.090892
28    0.339934  0.198164  0.076613  0.794165  0.241896
29    0.165941  0.224751  0.582694  0.767736  0.745386